apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kj6h
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kj6h
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kj6h
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kj6h
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kj6h
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dhrv-tenant/rhtap-demo-app/hacbs-test-project-kj6h@sha256:a99f28c69f2c5dce0ebfe33b6852ccc755cc26470ed7f18fd2dc7147508b38cd
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
