apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kj6h
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dhrv-tenant/rhtap-demo-app/hacbs-test-project-kj6h@sha256:a99f28c69f2c5dce0ebfe33b6852ccc755cc26470ed7f18fd2dc7147508b38cd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
